### ISSUE TITLE
comments of feeds got by "load more" don't display

### ISSUE THREAD

**Issue by chenkaiC4** [AdamBrodzinski/react-ive-meteor#12]
(sorry, my English is poor, specially in writing and listening. I hope I can give a clear description)

When I click "load more" bottom, five new Feeds will be loaded successfully. But the comments of these new Feeds disappear. 

I found that when sub completed, the postIds represent all current Feeds, but, we just can invoke it in next click of 'load more' or something else which will trigger reactive of pub/sub(e.x. click 'like' bottom) or change the state of Component(e.x. click 'load more' bottom).

we can go to http://react-ive.meteor.com/feed to see this bug.

the code with this bug:

``` js
startMeteorSubscriptions() {
    var fields = this.state.fieldsNeeded;
    var postIds = this.data.postIds;
    var recordCount = this.state.recordCount;
    return Meteor.subscribe("feed", fields, recordCount, postIds);
  },

  getMeteorData: function() {
    var sub = this.startMeteorSubscriptions();

    return {
      feedReady: sub.ready(),
      postItems: FeedDomain.getAllFeedPosts(),
      // ok, postIds are all here, but current sub can't use it any more, because sub is completed.
      postIds: FeedDomain.getPostCommentIds()
    };
  },
```

I have tried to fix this bug to get this demo better. The problem is that: very time "load more" bottom be clicked, the postIds passed to sub is collected among Feeds got in last sub. so the pub don't send the new Feeds's comments. So just let pub know the new Feeds, and update postIds.

``` js
  // current 'load more' postIds, 
  var loadMoreStep = 5;
  var newPostIds = Posts.find({}, {
                                  fields: {'_id': 1},
                                  sort: {createdAt: -1},
                                  limit: limits.posts,
                                  // just got new Feeds
                                  skip: limits.posts - loadMoreStep}
      ).map(function (post) {
        return post._id;
      });
  // update postIds
  postIds = _.union(postIds ? postIds : [], newPostIds);

  // returns Mongo Cursors
  return [
    Posts.find({}, {fields: fields.posts, sort: {createdAt: -1}, limit: limits.posts}),
    // postIds determines the comments sended to mini-mongo
    Comments.find({postId: {$in: postIds}}, {fields: fields.postComments})
  ];
```

I have create a PR #11, wish for review.

**Comment by AdamBrodzinski** [comment]
Awesome! I'm not going to be able to review it tonight but i'm hoping to look at it tomorrow night.

**Comment by chenkaiC4** [comment]
ha...I just get up. Please feel free to take these PRs by me, I am reading the demo code of meteor-flux-leaderboard by you, thanks to share your efforts, and nice night~

**Comment by AdamBrodzinski** [comment]
@chenkaiC4 haha sounds good. By the way you might want to checkout this new issue too:  
https://github.com/AdamBrodzinski/meteor-flux-leaderboard/issues/2
