### ISSUE TITLE
Redux Style

### ISSUE THREAD

**Issue by brandonmikeska** [AdamBrodzinski/react-ive-meteor#15]
I notice this is very similiar to a redux style. I notice the domains, but would moving that to reducers be possible?

**Comment by AdamBrodzinski** [comment]
Thanks! Yea that's the architecture I used in Blaze or React without Redux/flux. There isn't a single state object but the logic is in the domains folder.

I do want to migrate this to redux and make a branch but i've been pretty busy lately.

**Comment by brandonmikeska** [comment]
Yeah working on a social site and have it in rails, but looking to move to meteor and really trying to grasp my head around Meteor, React and Redux. I am getting Meteor and React down pretty quickly and easily, but the redux part is taking longer. Trying to figure out how to do an Authentication, currently using a passwordless login system, but that isn't the problem.

I am trying to grasp what should be the initial state for reducers and how to handle errors. Looking for examples and this seems pretty close, but it's not redux so maybe this along with your other repo might help!

**Comment by AdamBrodzinski** [comment]
> Trying to figure out how to do an Authentication, currently using a passwordless login system, but that isn't the problem.

Yea trying to shoehorn auth other than Meteor is an issue. Are you trying to use your current Rails auth?

> I am trying to grasp what should be the initial state for reducers and how to handle errors. Looking for examples and this seems pretty close, but it's not redux so maybe this along with your other repo might help!

Yea reducers can be a bit tricky. Have you tried the latest Redux readme? It's gotten a lot better!

So the initial state of a reducer can be anything. An empty array or an empty object, etc... Once you have multiple reducers they can merge together into a single object parent like this (note viewer reducer would initialize with {} and posts would init with []):

```
// global redux state
{
  posts: [],
  viewer: {},
}
```

Handling errors can be done in the action creator function (that's where side effects can happen). With mongo you can just dispatch an error action if it fails::

```
createPost = function(data) {
  Posts.insert(data, function(err, res) {
    if (err) {
      dispatch( AppActions.showError('Create Post failed') )
    }
  });
  return { type: 'CREATE_POST' };
}
```

Since minimongo handles optimistic updates we won't pass any data to the payload and if you're using the flux-helpers package it'll add data when the collection change event happens.

Hope this helps!

**Comment by brandonmikeska** [comment]
> Yea trying to shoehorn auth other than Meteor is an issue. Are you trying to use your current Rails auth?

Actually found this package https://github.com/efounders/meteor-accounts-passwordless and really only using it with the low level api. May just take what I need and remove the package.

> Yea reducers can be a bit tricky. Have you tried the latest Redux readme? It's gotten a lot better!

No I will do that as soon as I get to work :)

Apparently I need to read the docs again because I don't remember action creators, just actions.

If you were going to use the Meteor Login system, would you wrap that code in a reducer or just use it as is? Also routing, do you just do routing or keep that in a state so you can see where the user has gone and stuff? 

My apologies for all the questions, you can ignore them if you want haha.

**Comment by AdamBrodzinski** [comment]
So reducers only take raw data and merge them with the global state. They shouldn't fire any impure functions, so action creators would be the place for login. Then if you return a logged_in action perhaps you may want to toggle some state in a reducer that says logged in true or something like that.

Routing is still very uncertain... Hoping for them to finish their react router guide soon. For now I'm dispatching a goToPage action creator that just calls the go method

**Comment by brandonmikeska** [comment]
Thank you for all the answers. Your leaderboard redux example is proving to be a ton of help!

Hopefully the routing guide will come out soon!

**Comment by AdamBrodzinski** [comment]
Np! :beers:
