### ISSUE TITLE
http://react-meteor-tutorial.com/

### ISSUE THREAD

**Issue by paulwehner** [AdamBrodzinski/react-ive-meteor#16]
That link no longer works. Have you hosted the tutorial somewhere else?

**Comment by AdamBrodzinski** [comment]
@paulwehner ah, I thought I removed that lol. Is it in the readme? I decided not to produce the screencast series because there wasn't enough demand (although in hindsight perhaps I was too early). 

Cheers
Adam

**Comment by scottromack** [comment]
Hey, when you get a chance do a quick video on some of the react-meteor stuff. Very cool stuff.

**Comment by AdamBrodzinski** [comment]
@ShaggyDude i'm actually recording a few screencasts on migrating this project to 1.3 and adding some tests. should be done soon :smile:

**Comment by sahanDissanayake** [comment]
:+1:

**Comment by sahanDissanayake** [comment]
has meteor documented the domain model thing you are using here ? Its interesting, that everything for a model is is in one place

**Comment by AdamBrodzinski** [comment]
@sahanDissanayake  I don't think they've documented it anywhere. At one time I was going to create 'pattern' around this but I started using Redux (flux) so i'm only using this in legacy Meteor apps now. 

The general gist of the 'domain' area is that you can keep 'areas' of your app logic in one place, most importantly out of the UI. For instance, 'feed domain' is a group of models so it's more flexible than a 'controller' which is usually tied to a single model.

I've found that it's easier to maintain when you don't have to dig though template (Blaze/JSX) code to find out where something happened.

Cheeers
Adam

**Comment by sahanDissanayake** [comment]
thanks very much Adam for the explanation. Appreciate that :+1:

**Comment by scottycoupa** [comment]
That'll be great if you can update to Meteor 1.3 and Redux. Thanks!

**Comment by AdamBrodzinski** [comment]
@scottycoupa I agree! However I won't have time for at least several months. Very open to anyone making PRs for this :smiley:
