### ISSUE TITLE
Need better looking dates

### ISSUE THREAD

**Issue by AdamBrodzinski** [AdamBrodzinski/react-ive-meteor#4]
It should really use something like the Moment JS lib to say '3 hours ago' or even a properly formatted date.

**Comment by ghost** [comment]
https://github.com/yahoo/react-intl

**Comment by chenkaiC4** [comment]
Thanks for you nice demo,@AdamBrodzinski , and I hope I can contribute some code to make this demo better. I have enhanced the display of date like '3 hours ago' with a mixins in FeedItemHeader, but in CommentItem, which create by `extends React.Component`, mixins is not supported. I will set a PR, hope to discuss with you to solve it.

**Comment by AdamBrodzinski** [comment]
closing, merged #9 Thanks again @chenkaiC4 !
