### ISSUE TITLE
Install error with scss

### ISSUE THREAD

**Issue by rozzzly** [AdamBrodzinski/react-ive-meteor#5]
When doing a fresh install with, `git clone https://github.com/AdamBrodzinski/react-ive-meteor`.  I got the following error:

```
[rozzzly@digitalsea react-ive-meteor]$ meteor
[[[[[ /var/www/react-ive-meteor ]]]]]

=> Started proxy.
=> Started MongoDB.
=> Errors prevented startup:

   While building the application:
   /var/www/react-ive-meteor/client/styles/_components.scss:4:9: Scss compiler error: file to import not found or unreadable: ../components/paramsExample/paramsExample
   Current dir: /var/www/react-ive-meteor/client/styles/


=> Your application has errors. Waiting for file change.
```

It looks like the `scss` compiler is unable to load that file. After inspection, it appears that the issue is with a difference in the casing in the file name. I have resolved the issue and will submit a pull request shortly.

**Comment by AdamBrodzinski** [comment]
Fix merged to master. The camel SCSS casing was from using the Meteor-Generate CLI. That should be fixed soon as well.
